%% IPiezo (Forouzandehmehr et al., 2023: https://doi.org/10.22489/CinC.2023.359)
% Author: Amin Forouzandehmehr

E_P = 0;            % Volt 55e-3 from Paulina Czarnecki OR 0 mV from https://doi.org/10.1073/pnas.2215747120 and https://doi.org/10.1038/s41467-023-36931-0
g_p = 0.3039;           % S/F from: https://doi.org/10.1038/s41467-023-36931-0
tau_p = 0.1;            % Time constant
cf = 0.5*1.1626e-01;    % The conversion factor Cm/(2F*Vc*1e-18): A/F to mM/s
%d = 1.75;              % The indentation (displacement) micrometer 0 to 5 or the "frc"-dependent d or
%d= (Y(32)/1.9)*5;      % Normalized dynamic sarcomere length 
d = (frc/0.056) * 5;    % frc is the tension generated by the myofilament model
mpi = 1.0/(1+exp(-(d-2.5)/0.25)); 
dY(34,1) = (mpi-Y(34))/tau_p;

% Voltage-dependent inactivation 
Xs_inf = 2.0/(1.0+exp((-Y(1)*1000.0-0.0)/16.0)); 
al_Xs    = 1/sqrt(1.0+exp((-60.0+Y(1)*1000.0)/50.0)); 
be_Xs     = 900.0/(1.0+exp((+171.0-Y(1)*1000.0)/72.0)); 
ta_Xs      = coeff_Q10_generico_tau * 30.0*al_Xs*be_Xs/100.0;
dY(35, 1)   = (Xs_inf-Y(35))/ta_Xs;

i_Pie = 1 * g_p*Y(34)*Y(35)*(Y(1)-E_P);       % IPiezo1 (A/F)
Jpiezo = 1* i_Pie * cf;                     % Ca2+ flux of Piezo1 (mM/s)
mm = ta_Xs;                                   % Inactivation 

% Example of the integration of Jpiezo into dCai/dt of a cell:
%Cai
%dY(3,1) = Cai_bufc * (i_leak - i_up + i_rel - ((i_CaL + i_b_Ca + i_PCa - 2.0*i_NaCa + Jpizeo) * Cm / (2.0 * Vc * F * 1.0e-18)) - JCaBMyo);
